// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dpr/dpr.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Dpr struct {
	Id             string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Creator        string `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	SupportedPIDs  string `protobuf:"bytes,3,opt,name=supportedPIDs,proto3" json:"supportedPIDs,omitempty"`
	IsActive       bool   `protobuf:"varint,4,opt,name=isActive,proto3" json:"isActive,omitempty"`
	Duration       uint64 `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	DprEndTime     string `protobuf:"bytes,6,opt,name=dprEndTime,proto3" json:"dprEndTime,omitempty"`
	DprStartEpoch  uint64 `protobuf:"varint,7,opt,name=dprStartEpoch,proto3" json:"dprStartEpoch,omitempty"`
	DprBudget      string `protobuf:"bytes,8,opt,name=dprBudget,proto3" json:"dprBudget,omitempty"`
	MaxClientCount uint64 `protobuf:"varint,9,opt,name=maxClientCount,proto3" json:"maxClientCount,omitempty"`
	ClientCounter  uint64 `protobuf:"varint,10,opt,name=clientCounter,proto3" json:"clientCounter,omitempty"`
}

func (m *Dpr) Reset()         { *m = Dpr{} }
func (m *Dpr) String() string { return proto.CompactTextString(m) }
func (*Dpr) ProtoMessage()    {}
func (*Dpr) Descriptor() ([]byte, []int) {
	return fileDescriptor_221c37c1dd019f8d, []int{0}
}
func (m *Dpr) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Dpr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Dpr.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Dpr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dpr.Merge(m, src)
}
func (m *Dpr) XXX_Size() int {
	return m.Size()
}
func (m *Dpr) XXX_DiscardUnknown() {
	xxx_messageInfo_Dpr.DiscardUnknown(m)
}

var xxx_messageInfo_Dpr proto.InternalMessageInfo

func (m *Dpr) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Dpr) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Dpr) GetSupportedPIDs() string {
	if m != nil {
		return m.SupportedPIDs
	}
	return ""
}

func (m *Dpr) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *Dpr) GetDuration() uint64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Dpr) GetDprEndTime() string {
	if m != nil {
		return m.DprEndTime
	}
	return ""
}

func (m *Dpr) GetDprStartEpoch() uint64 {
	if m != nil {
		return m.DprStartEpoch
	}
	return 0
}

func (m *Dpr) GetDprBudget() string {
	if m != nil {
		return m.DprBudget
	}
	return ""
}

func (m *Dpr) GetMaxClientCount() uint64 {
	if m != nil {
		return m.MaxClientCount
	}
	return 0
}

func (m *Dpr) GetClientCounter() uint64 {
	if m != nil {
		return m.ClientCounter
	}
	return 0
}

func init() {
	proto.RegisterType((*Dpr)(nil), "soarchain.dpr.Dpr")
}

func init() { proto.RegisterFile("dpr/dpr.proto", fileDescriptor_221c37c1dd019f8d) }

var fileDescriptor_221c37c1dd019f8d = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x86, 0x3b, 0x69, 0xbf, 0xfe, 0x0c, 0xb4, 0x8b, 0x81, 0x0f, 0x06, 0x91, 0xa1, 0x88, 0x48,
	0x56, 0xcd, 0xc2, 0x2b, 0xb0, 0x3f, 0x0b, 0x77, 0x12, 0x5d, 0xb9, 0x1b, 0x73, 0x06, 0x3b, 0x60,
	0x33, 0x87, 0x93, 0x89, 0xd4, 0xbb, 0xf0, 0x8e, 0xdc, 0xba, 0xec, 0xd2, 0xa5, 0x24, 0x37, 0x22,
	0x19, 0x31, 0x35, 0x2e, 0xdf, 0xe7, 0xc0, 0xf3, 0xc2, 0x79, 0xf9, 0x14, 0x90, 0x12, 0x40, 0x5a,
	0x20, 0x39, 0xef, 0xc4, 0xb4, 0x70, 0x9a, 0xb2, 0xad, 0xb6, 0xf9, 0x02, 0x90, 0xce, 0xde, 0x22,
	0xde, 0x5f, 0x23, 0x89, 0x19, 0x8f, 0x2c, 0x48, 0x36, 0x67, 0xf1, 0x24, 0x8d, 0x2c, 0x08, 0xc9,
	0x47, 0x19, 0x19, 0xed, 0x1d, 0xc9, 0x28, 0xc0, 0x9f, 0x28, 0xce, 0xf9, 0xb4, 0x28, 0x11, 0x1d,
	0x79, 0x03, 0x37, 0xd7, 0xeb, 0x42, 0xf6, 0xc3, 0xbd, 0x0b, 0xc5, 0x09, 0x1f, 0xdb, 0xe2, 0x2a,
	0xf3, 0xf6, 0xd9, 0xc8, 0xc1, 0x9c, 0xc5, 0xe3, 0xb4, 0xcd, 0xcd, 0x0d, 0x4a, 0xd2, 0xde, 0xba,
	0x5c, 0xfe, 0x9b, 0xb3, 0x78, 0x90, 0xb6, 0x59, 0x28, 0xce, 0x01, 0x69, 0x93, 0xc3, 0x9d, 0xdd,
	0x19, 0x39, 0x0c, 0xea, 0x5f, 0xa4, 0x69, 0x07, 0xa4, 0x5b, 0xaf, 0xc9, 0x6f, 0xd0, 0x65, 0x5b,
	0x39, 0x0a, 0x82, 0x2e, 0x14, 0xa7, 0x7c, 0x02, 0x48, 0xcb, 0x12, 0x1e, 0x8d, 0x97, 0xe3, 0x20,
	0x39, 0x02, 0x71, 0xc1, 0x67, 0x3b, 0xbd, 0x5f, 0x3d, 0x59, 0x93, 0xfb, 0x95, 0x2b, 0x73, 0x2f,
	0x27, 0x41, 0xf2, 0x87, 0x36, 0x5d, 0xd9, 0x31, 0x1a, 0x92, 0xfc, 0xbb, 0xab, 0x03, 0x97, 0xc9,
	0x7b, 0xa5, 0xd8, 0xa1, 0x52, 0xec, 0xb3, 0x52, 0xec, 0xb5, 0x56, 0xbd, 0x43, 0xad, 0x7a, 0x1f,
	0xb5, 0xea, 0xdd, 0xff, 0x6f, 0x5f, 0x9d, 0xec, 0x9b, 0x05, 0x12, 0xff, 0x82, 0xa6, 0x78, 0x18,
	0x86, 0x21, 0x2e, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x87, 0x53, 0xe8, 0x46, 0x99, 0x01, 0x00,
	0x00,
}

func (m *Dpr) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Dpr) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Dpr) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ClientCounter != 0 {
		i = encodeVarintDpr(dAtA, i, uint64(m.ClientCounter))
		i--
		dAtA[i] = 0x50
	}
	if m.MaxClientCount != 0 {
		i = encodeVarintDpr(dAtA, i, uint64(m.MaxClientCount))
		i--
		dAtA[i] = 0x48
	}
	if len(m.DprBudget) > 0 {
		i -= len(m.DprBudget)
		copy(dAtA[i:], m.DprBudget)
		i = encodeVarintDpr(dAtA, i, uint64(len(m.DprBudget)))
		i--
		dAtA[i] = 0x42
	}
	if m.DprStartEpoch != 0 {
		i = encodeVarintDpr(dAtA, i, uint64(m.DprStartEpoch))
		i--
		dAtA[i] = 0x38
	}
	if len(m.DprEndTime) > 0 {
		i -= len(m.DprEndTime)
		copy(dAtA[i:], m.DprEndTime)
		i = encodeVarintDpr(dAtA, i, uint64(len(m.DprEndTime)))
		i--
		dAtA[i] = 0x32
	}
	if m.Duration != 0 {
		i = encodeVarintDpr(dAtA, i, uint64(m.Duration))
		i--
		dAtA[i] = 0x28
	}
	if m.IsActive {
		i--
		if m.IsActive {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if len(m.SupportedPIDs) > 0 {
		i -= len(m.SupportedPIDs)
		copy(dAtA[i:], m.SupportedPIDs)
		i = encodeVarintDpr(dAtA, i, uint64(len(m.SupportedPIDs)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintDpr(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintDpr(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDpr(dAtA []byte, offset int, v uint64) int {
	offset -= sovDpr(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Dpr) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovDpr(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovDpr(uint64(l))
	}
	l = len(m.SupportedPIDs)
	if l > 0 {
		n += 1 + l + sovDpr(uint64(l))
	}
	if m.IsActive {
		n += 2
	}
	if m.Duration != 0 {
		n += 1 + sovDpr(uint64(m.Duration))
	}
	l = len(m.DprEndTime)
	if l > 0 {
		n += 1 + l + sovDpr(uint64(l))
	}
	if m.DprStartEpoch != 0 {
		n += 1 + sovDpr(uint64(m.DprStartEpoch))
	}
	l = len(m.DprBudget)
	if l > 0 {
		n += 1 + l + sovDpr(uint64(l))
	}
	if m.MaxClientCount != 0 {
		n += 1 + sovDpr(uint64(m.MaxClientCount))
	}
	if m.ClientCounter != 0 {
		n += 1 + sovDpr(uint64(m.ClientCounter))
	}
	return n
}

func sovDpr(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDpr(x uint64) (n int) {
	return sovDpr(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Dpr) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDpr
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Dpr: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Dpr: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDpr
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDpr
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDpr
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDpr
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDpr
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDpr
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SupportedPIDs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDpr
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDpr
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDpr
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SupportedPIDs = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsActive", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDpr
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsActive = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			m.Duration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDpr
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Duration |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DprEndTime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDpr
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDpr
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDpr
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DprEndTime = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DprStartEpoch", wireType)
			}
			m.DprStartEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDpr
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DprStartEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DprBudget", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDpr
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDpr
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDpr
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DprBudget = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxClientCount", wireType)
			}
			m.MaxClientCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDpr
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxClientCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientCounter", wireType)
			}
			m.ClientCounter = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDpr
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClientCounter |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDpr(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDpr
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDpr(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDpr
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDpr
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDpr
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDpr
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDpr
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDpr
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDpr        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDpr          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDpr = fmt.Errorf("proto: unexpected end of group")
)
