accounts:
  - name: alice
    coins: ["50000000soar"]
  - name: bob
    coins: ["5000000soar"]
  - name: can
    coins: ["10000000soar"]
  - name: amir
    coins: ["20000000soar"]
validator:
  name: alice
  staked: "10000000soar"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["20000soar"]
genesis:
  app_state:
    staking:
      params:
        bond_denom: "soar"