accounts:
  - name: alice
    coins: ["50000000soar"]
  - name: bob
    coins: ["5000000soar"]
  - name: can
    coins: ["10000000soar"]
  - name: amir
    coins: ["20000000soar"]
  - name: v2xDevice1
    coins: ["10soar"]
  - name: v2nDevice1
    coins: ["10soar"]
  - name: runnerDevice1
    coins: ["10soar"]
  - name: v2xDevice2
    coins: ["10soar"]
  - name: v2nDevice2
    coins: ["10soar"]
  - name: runnerDevice2
    coins: ["10soar"]
validator:
  name: alice
  staked: "10000000soar"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["20000soar"]
genesis:
  app_state:
    staking:
      params:
        bond_denom: "soar"
    mint:
      params:
        mint_denom: "soar"
        goal_bonded: "0.670000000000000000"
        inflation_max: "0.200000000000000000"
        inflation_min: "0.120000000000000000"
        inflation_rate_change: "0.080000000000000000"
      minter:
        inflation: "0.080000000000000000"