// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: poa/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the poa module's genesis state.
type GenesisState struct {
	Params                Params              `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	ClientList            []Client            `protobuf:"bytes,2,rep,name=clientList,proto3" json:"clientList"`
	ChallengerList        []Challenger        `protobuf:"bytes,3,rep,name=challengerList,proto3" json:"challengerList"`
	RunnerList            []Runner            `protobuf:"bytes,4,rep,name=runnerList,proto3" json:"runnerList"`
	GuardList             []Guard             `protobuf:"bytes,5,rep,name=guardList,proto3" json:"guardList"`
	TotalClients          TotalClients        `protobuf:"bytes,6,opt,name=totalClients,proto3" json:"totalClients"`
	TotalChallengers      TotalChallengers    `protobuf:"bytes,7,opt,name=totalChallengers,proto3" json:"totalChallengers"`
	TotalRunners          TotalRunners        `protobuf:"bytes,8,opt,name=totalRunners,proto3" json:"totalRunners"`
	ChallengerByIndexList []ChallengerByIndex `protobuf:"bytes,9,rep,name=challengerByIndexList,proto3" json:"challengerByIndexList"`
	RunnerByIndexList     []RunnerByIndex     `protobuf:"bytes,10,rep,name=runnerByIndexList,proto3" json:"runnerByIndexList"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c9d5a9eb5268c7b, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetClientList() []Client {
	if m != nil {
		return m.ClientList
	}
	return nil
}

func (m *GenesisState) GetChallengerList() []Challenger {
	if m != nil {
		return m.ChallengerList
	}
	return nil
}

func (m *GenesisState) GetRunnerList() []Runner {
	if m != nil {
		return m.RunnerList
	}
	return nil
}

func (m *GenesisState) GetGuardList() []Guard {
	if m != nil {
		return m.GuardList
	}
	return nil
}

func (m *GenesisState) GetTotalClients() TotalClients {
	if m != nil {
		return m.TotalClients
	}
	return TotalClients{}
}

func (m *GenesisState) GetTotalChallengers() TotalChallengers {
	if m != nil {
		return m.TotalChallengers
	}
	return TotalChallengers{}
}

func (m *GenesisState) GetTotalRunners() TotalRunners {
	if m != nil {
		return m.TotalRunners
	}
	return TotalRunners{}
}

func (m *GenesisState) GetChallengerByIndexList() []ChallengerByIndex {
	if m != nil {
		return m.ChallengerByIndexList
	}
	return nil
}

func (m *GenesisState) GetRunnerByIndexList() []RunnerByIndex {
	if m != nil {
		return m.RunnerByIndexList
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "soarchain.poa.GenesisState")
}

func init() { proto.RegisterFile("poa/genesis.proto", fileDescriptor_5c9d5a9eb5268c7b) }

var fileDescriptor_5c9d5a9eb5268c7b = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xcf, 0x6b, 0xe2, 0x40,
	0x14, 0xc7, 0x93, 0xf5, 0xc7, 0xae, 0xb3, 0xee, 0xae, 0x0e, 0xca, 0x46, 0xdd, 0x8d, 0xd2, 0x53,
	0x4f, 0x09, 0xd4, 0x4b, 0xa1, 0x37, 0x4b, 0x91, 0x42, 0x0f, 0xd6, 0xf6, 0x54, 0x0a, 0x32, 0xea,
	0x10, 0x03, 0x69, 0x26, 0x64, 0x22, 0xe8, 0x7f, 0xd1, 0x3f, 0xcb, 0xa3, 0xbd, 0xf5, 0x54, 0x8a,
	0xfe, 0x23, 0x25, 0x6f, 0xc6, 0xfc, 0x32, 0xde, 0xf4, 0xbd, 0xef, 0xf7, 0xe3, 0xf7, 0xbd, 0xe7,
	0xa0, 0xba, 0xc7, 0x88, 0x69, 0x51, 0x97, 0x72, 0x9b, 0x1b, 0x9e, 0xcf, 0x02, 0x86, 0x7f, 0x71,
	0x46, 0xfc, 0xd9, 0x82, 0xd8, 0xae, 0xe1, 0x31, 0xd2, 0x6e, 0x58, 0xcc, 0x62, 0xd0, 0x31, 0xc3,
	0x4f, 0x42, 0xd4, 0xae, 0x85, 0x3e, 0x8f, 0xf8, 0xe4, 0x85, 0x27, 0x2b, 0x33, 0xc7, 0xa6, 0x6e,
	0x20, 0x2b, 0x0d, 0xa8, 0x2c, 0x88, 0xe3, 0x50, 0xd7, 0xa2, 0x7e, 0x52, 0xe7, 0x2f, 0x5d, 0x37,
	0xaa, 0xfc, 0x81, 0x0c, 0x4b, 0xe2, 0xcf, 0x65, 0xe1, 0x6f, 0x58, 0x08, 0x58, 0x40, 0x9c, 0x89,
	0x00, 0x1e, 0x7e, 0xa3, 0x93, 0x68, 0x44, 0x5c, 0x7e, 0xec, 0x12, 0xf8, 0x43, 0xe3, 0x7f, 0x3a,
	0xc7, 0x64, 0xba, 0x9e, 0xd8, 0xee, 0x9c, 0xae, 0x64, 0xbb, 0x15, 0x07, 0xca, 0xb4, 0xce, 0xde,
	0x4a, 0xa8, 0x3a, 0x14, 0xcb, 0x79, 0x08, 0x48, 0x40, 0x71, 0x1f, 0x95, 0xc5, 0xd0, 0x9a, 0xda,
	0x53, 0xcf, 0x7f, 0x5e, 0x34, 0x8d, 0xd4, 0xb2, 0x8c, 0x11, 0x34, 0x07, 0xc5, 0xcd, 0x47, 0x57,
	0x19, 0x4b, 0x29, 0xbe, 0x42, 0x48, 0x8c, 0x71, 0x67, 0xf3, 0x40, 0xfb, 0xd6, 0x2b, 0xe4, 0x18,
	0xaf, 0x41, 0x20, 0x8d, 0x09, 0x39, 0x1e, 0xa2, 0xdf, 0x71, 0x74, 0x00, 0x14, 0x00, 0xd0, 0xca,
	0x02, 0x22, 0x91, 0x84, 0x64, 0x6c, 0x61, 0x0a, 0x31, 0x24, 0x40, 0x8a, 0xb9, 0x29, 0xc6, 0x20,
	0x38, 0xa4, 0x88, 0xe5, 0xf8, 0x12, 0x55, 0xe0, 0x40, 0xe0, 0x2d, 0x81, 0xb7, 0x91, 0xf1, 0x0e,
	0xc3, 0xbe, 0xb4, 0xc6, 0x62, 0x7c, 0x83, 0xaa, 0x70, 0x13, 0x31, 0x20, 0xd7, 0xca, 0xb0, 0xb7,
	0x4e, 0xc6, 0xfc, 0x98, 0x90, 0x48, 0x46, 0xca, 0x86, 0xef, 0x51, 0x4d, 0x7c, 0x8f, 0xcf, 0xae,
	0x7d, 0x07, 0x54, 0x37, 0x17, 0x15, 0xcb, 0x24, 0xee, 0xc8, 0x1e, 0x25, 0x13, 0x43, 0x73, 0xed,
	0xc7, 0xe9, 0x64, 0x52, 0x92, 0x4a, 0x26, 0x6b, 0xf8, 0x19, 0x35, 0xe3, 0x4d, 0x0f, 0xd6, 0xb7,
	0xe1, 0xdf, 0x07, 0xd6, 0x54, 0x81, 0x35, 0xf5, 0x4e, 0xdf, 0x49, 0x68, 0x25, 0x34, 0x1f, 0x82,
	0x47, 0xa8, 0x2e, 0xce, 0x90, 0x24, 0x23, 0x20, 0xff, 0xcb, 0x3f, 0x5e, 0x8a, 0x7a, 0x6c, 0x1e,
	0x98, 0x9b, 0x9d, 0xae, 0x6e, 0x77, 0xba, 0xfa, 0xb9, 0xd3, 0xd5, 0xd7, 0xbd, 0xae, 0x6c, 0xf7,
	0xba, 0xf2, 0xbe, 0xd7, 0x95, 0xa7, 0x66, 0xc4, 0x33, 0x57, 0x26, 0x3c, 0xa6, 0xb5, 0x47, 0xf9,
	0xb4, 0x0c, 0x6f, 0xa1, 0xff, 0x15, 0x00, 0x00, 0xff, 0xff, 0x76, 0x49, 0xb8, 0x8f, 0x2b, 0x04,
	0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RunnerByIndexList) > 0 {
		for iNdEx := len(m.RunnerByIndexList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RunnerByIndexList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.ChallengerByIndexList) > 0 {
		for iNdEx := len(m.ChallengerByIndexList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ChallengerByIndexList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	{
		size, err := m.TotalRunners.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size, err := m.TotalChallengers.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size, err := m.TotalClients.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.GuardList) > 0 {
		for iNdEx := len(m.GuardList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GuardList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.RunnerList) > 0 {
		for iNdEx := len(m.RunnerList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RunnerList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.ChallengerList) > 0 {
		for iNdEx := len(m.ChallengerList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ChallengerList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.ClientList) > 0 {
		for iNdEx := len(m.ClientList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ClientList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.ClientList) > 0 {
		for _, e := range m.ClientList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ChallengerList) > 0 {
		for _, e := range m.ChallengerList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RunnerList) > 0 {
		for _, e := range m.RunnerList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.GuardList) > 0 {
		for _, e := range m.GuardList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.TotalClients.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.TotalChallengers.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.TotalRunners.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.ChallengerByIndexList) > 0 {
		for _, e := range m.ChallengerByIndexList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RunnerByIndexList) > 0 {
		for _, e := range m.RunnerByIndexList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientList = append(m.ClientList, Client{})
			if err := m.ClientList[len(m.ClientList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengerList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChallengerList = append(m.ChallengerList, Challenger{})
			if err := m.ChallengerList[len(m.ChallengerList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RunnerList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RunnerList = append(m.RunnerList, Runner{})
			if err := m.RunnerList[len(m.RunnerList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GuardList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GuardList = append(m.GuardList, Guard{})
			if err := m.GuardList[len(m.GuardList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalClients", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalClients.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalChallengers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalChallengers.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalRunners", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalRunners.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengerByIndexList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChallengerByIndexList = append(m.ChallengerByIndexList, ChallengerByIndex{})
			if err := m.ChallengerByIndexList[len(m.ChallengerByIndexList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RunnerByIndexList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RunnerByIndexList = append(m.RunnerByIndexList, RunnerByIndex{})
			if err := m.RunnerByIndexList[len(m.RunnerByIndexList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
