// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: poa/runner_by_index.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RunnerByIndex struct {
	Index  string  `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Runner *Runner `protobuf:"bytes,2,opt,name=runner,proto3" json:"runner,omitempty"`
}

func (m *RunnerByIndex) Reset()         { *m = RunnerByIndex{} }
func (m *RunnerByIndex) String() string { return proto.CompactTextString(m) }
func (*RunnerByIndex) ProtoMessage()    {}
func (*RunnerByIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac66eadcc6b8ace0, []int{0}
}
func (m *RunnerByIndex) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RunnerByIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RunnerByIndex.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RunnerByIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunnerByIndex.Merge(m, src)
}
func (m *RunnerByIndex) XXX_Size() int {
	return m.Size()
}
func (m *RunnerByIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_RunnerByIndex.DiscardUnknown(m)
}

var xxx_messageInfo_RunnerByIndex proto.InternalMessageInfo

func (m *RunnerByIndex) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *RunnerByIndex) GetRunner() *Runner {
	if m != nil {
		return m.Runner
	}
	return nil
}

func init() {
	proto.RegisterType((*RunnerByIndex)(nil), "soarchain.poa.RunnerByIndex")
}

func init() { proto.RegisterFile("poa/runner_by_index.proto", fileDescriptor_ac66eadcc6b8ace0) }

var fileDescriptor_ac66eadcc6b8ace0 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0xc8, 0x4f, 0xd4,
	0x2f, 0x2a, 0xcd, 0xcb, 0x4b, 0x2d, 0x8a, 0x4f, 0xaa, 0x8c, 0xcf, 0xcc, 0x4b, 0x49, 0xad, 0xd0,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2d, 0xce, 0x4f, 0x2c, 0x4a, 0xce, 0x48, 0xcc, 0xcc,
	0xd3, 0x2b, 0xc8, 0x4f, 0x94, 0x12, 0x40, 0xa8, 0x84, 0x28, 0x50, 0x0a, 0xe1, 0xe2, 0x0d, 0x02,
	0xf3, 0x9d, 0x2a, 0x3d, 0x41, 0xfa, 0x84, 0x44, 0xb8, 0x58, 0xc1, 0x06, 0x48, 0x30, 0x2a, 0x30,
	0x6a, 0x70, 0x06, 0x41, 0x38, 0x42, 0xba, 0x5c, 0x6c, 0x10, 0x6d, 0x12, 0x4c, 0x0a, 0x8c, 0x1a,
	0xdc, 0x46, 0xa2, 0x7a, 0x28, 0x06, 0xeb, 0x41, 0xcc, 0x08, 0x82, 0x2a, 0x72, 0xd2, 0x3f, 0xf1,
	0x48, 0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07, 0x8f, 0xe4, 0x18, 0x27, 0x3c, 0x96, 0x63, 0xb8,
	0xf0, 0x58, 0x8e, 0xe1, 0xc6, 0x63, 0x39, 0x86, 0x28, 0x51, 0xb8, 0x3e, 0xfd, 0x0a, 0x7d, 0x90,
	0x6b, 0x4a, 0x2a, 0x0b, 0x52, 0x8b, 0x93, 0xd8, 0xc0, 0xae, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x15, 0xdd, 0xa0, 0x1b, 0xcb, 0x00, 0x00, 0x00,
}

func (m *RunnerByIndex) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RunnerByIndex) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RunnerByIndex) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Runner != nil {
		{
			size, err := m.Runner.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRunnerByIndex(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintRunnerByIndex(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintRunnerByIndex(dAtA []byte, offset int, v uint64) int {
	offset -= sovRunnerByIndex(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RunnerByIndex) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovRunnerByIndex(uint64(l))
	}
	if m.Runner != nil {
		l = m.Runner.Size()
		n += 1 + l + sovRunnerByIndex(uint64(l))
	}
	return n
}

func sovRunnerByIndex(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRunnerByIndex(x uint64) (n int) {
	return sovRunnerByIndex(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RunnerByIndex) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRunnerByIndex
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RunnerByIndex: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RunnerByIndex: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRunnerByIndex
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRunnerByIndex
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRunnerByIndex
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Runner", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRunnerByIndex
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRunnerByIndex
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRunnerByIndex
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Runner == nil {
				m.Runner = &Runner{}
			}
			if err := m.Runner.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRunnerByIndex(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRunnerByIndex
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRunnerByIndex(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRunnerByIndex
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRunnerByIndex
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRunnerByIndex
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRunnerByIndex
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRunnerByIndex
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRunnerByIndex
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRunnerByIndex        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRunnerByIndex          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRunnerByIndex = fmt.Errorf("proto: unexpected end of group")
)
