name: Deploy Node
on: ["push"]

jobs:
  ci:
    runs-on: ubuntu-latest
    continue-on-error: true

    permissions:
        contents: read
        packages: write
    strategy:
        fail-fast: false
        matrix:
          go: ["1.18.x"]
          dir: ["x"]  
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Tests
        run: "go test ./..."
      
      - name: Qualify Code
        run: "go vet ./..."
      
      - name: Run static check  
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.3"

      - name: Prepare Remote Server
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: 34.105.137.35
            username: golnar
            key: ${{ secrets.SSH_PRIVATEKEY }}
            script: |
                  result=$(docker ps -a -q)
                  if [[ -n "$result" ]]; then
                    echo 'Container exists'
                    docker stop $(docker ps -a -q)
                    docker rm $(docker ps -a -q)
                  fi
                  result=$( sudo docker images -q soarchain-core )
                  if [[ -n "$result" ]]; then
                    echo 'Container image exists'
                    docker rmi soarchain-core:0.1.0
                  fi
                  FILE= ~/soarchain-core
                  if [ -d "$FILE" ]; then
                    echo "$FILE is a directory."
                    rm -r ~/soarchain-core
                  fi
      - name: Copy folder content recursively to remote
        uses: appleboy/scp-action@master
        with:
            host: 34.105.137.35
            username: golnar
            key: ${{ secrets.SSH_PRIVATEKEY }}
            source: "./*"
            target: "/home/golnar/soarchain-core"
            debug: true
            
      - name: Deploy Node
        continue-on-error: true
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: 34.105.137.35
            username: golnar
            key: ${{ secrets.SSH_PRIVATEKEY }}
            command_timeout: 4m
            script: |
                cd ~/soarchain-core
                docker compose -f docker-compose.ci.yml up
                echo "Nice Job!!!"
