name: Test and Publish
on:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: go test ./x/*
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for Master Branch
        run: |
          if ! git rev-parse --verify master > /dev/null 2>&1; then
            git checkout -b master
          fi
      - name: Push to Master
        run: git push origin master
